### ISSUE TITLE
La documentation Sur Js

### ISSUE THREAD

**Issue by yocho1** [yocho1/Js_Mini_Projects#2]
1-Gulp [Look Her a Drariiiiiiii](https://developers.google.com/web/ilt/pwa/introduction-to-gulp)
2-Les variables [Loooooook](https://openclassrooms.com/fr/courses/2984401-apprenez-a-coder-avec-javascript/3039191-jouez-avec-les-variables)
3-les fonctions [Loookk](https://developer.mozilla.org/fr/docs/Web/JavaScript/Guide/Fonctions)
4-les conditions [Ta LOOOOOK](https://openclassrooms.com/fr/courses/1916641-dynamisez-vos-sites-web-avec-javascript/1917384-les-conditions)
5-les opérateurs [Seeee](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Op%C3%A9rateurs)
6-Objects
7-DOM

**Comment by walidhar** [comment]
GULP : https://www.alsacreations.com/tuto/lire/1686-introduction-a-gulp.html

**Comment by abderrahmanerouah** [comment]
GULP : https://www.youtube.com/watch?time_continue=16&v=-Q5v14O3Bmk&feature=emb_logo
